In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()
df=pd.read_csv('sales_data_sample.csv', encoding='latin-1')

Saving sales_data_sample.csv to sales_data_sample.csv

In [4]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [5]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [6]:
df.tail()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [7]:
df.shape

(2823, 25)

In [8]:
df.isnull().sum()/df.shape[0]*100

ORDERNUMBER          0.000000
QUANTITYORDERED      0.000000
PRICEEACH            0.000000
ORDERLINENUMBER      0.000000
SALES                0.000000
ORDERDATE            0.000000
STATUS               0.000000
QTR_ID               0.000000
MONTH_ID             0.000000
YEAR_ID              0.000000
PRODUCTLINE          0.000000
MSRP                 0.000000
PRODUCTCODE          0.000000
CUSTOMERNAME         0.000000
PHONE                0.000000
ADDRESSLINE1         0.000000
ADDRESSLINE2        89.302161
CITY                 0.000000
STATE               52.639036
POSTALCODE           2.692171
COUNTRY              0.000000
TERRITORY           38.044633
CONTACTLASTNAME      0.000000
CONTACTFIRSTNAME     0.000000
DEALSIZE             0.000000
dtype: float64

In [9]:
#df.drop('ADDRESSLINE2', axis=1, inplace=True)
df.dropna(thresh=int(100-60/100)*df.shape[1], axis=1,inplace =True)
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'CITY', 'POSTALCODE', 'COUNTRY', 'CONTACTLASTNAME',
       'CONTACTFIRSTNAME', 'DEALSIZE'],
      dtype='object')

In [10]:
df['POSTALCODE'].fillna(df['POSTALCODE'], inplace=True)

In [11]:
# prompt: fill with the above one

df['POSTALCODE'].fillna('unknown')

0         10022
1         51100
2         75508
3         90003
4       unknown
         ...
2818      28034
2819      90110
2820      28034
2821      31000
2822      51003
Name: POSTALCODE, Length: 2823, dtype: object

In [12]:
df['ORDERNUMBER'].unique()
df['ORDERNUMBER'].nunique()

307

In [13]:
df[df['STATUS']=='Shipped']

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,S72_3212,La Rochelle Gifts,40.67.8555,"67, rue des Cinquante Otages",Nantes,44000,France,Labrune,Janine,Small
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,S72_3212,Classic Legends Inc.,2125558493,5905 Pompton St.,NYC,10022,USA,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small

In [14]:
df[(df['PRODUCTLINE']=='Motorcycles') & (df['STATUS']=='Shipped')]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,10356,26,100.00,4,3937.70,12/9/2004 0:00,Shipped,4,12,2004,...,S50_4713,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
2453,10365,44,100.00,2,4984.32,1/7/2005 0:00,Shipped,1,1,2005,...,S50_4713,Mini Creations Ltd.,5085559555,4575 Hillside Dr.,New Bedford,50553,USA,Tam,Wing C,Medium
2454,10375,49,100.00,8,5406.66,2/3/2005 0:00,Shipped,1,2,2005,...,S50_4713,La Rochelle Gifts,40.67.8555,"67, rue des Cinquante Otages",Nantes,44000,France,Labrune,Janine,Medium
2455,10390,22,100.00,13,3491.18,3/4/2005 0:00,Shipped,1,3,2005,...,S50_4713,Mini Gifts Distributors Ltd.,4155551450,5677 Strong St.,San Rafael,97562,USA,Nelson,Valarie,Medium
2456,10403,31,68.34,3,2118.54,4/8/2005 0:00,Shipped,2,4,2005,...,S50_4713,"UK Collectables, Ltd.",(171) 555-2282,Berkeley Gardens 12 Brewery,Liverpool,WX1 6LT,UK,Devon,Elizabeth,Small

In [15]:
df[df['SALES']>4000][['ORDERNUMBER','SALES','ORDERDATE']]

      ORDERNUMBER    SALES        ORDERDATE
4           10159  5205.27  10/10/2003 0:00
7           10188  5512.32  11/18/2003 0:00
9           10211  4708.44   1/15/2004 0:00
14          10275  4177.35   7/23/2004 0:00
15          10285  4099.68   8/27/2004 0:00
...           ...      ...              ...
2758        10296  4071.14   9/15/2004 0:00
2764        10361  4277.35  12/17/2004 0:00
2793        10386  4357.50    3/1/2005 0:00
2817        10337  4080.72  11/21/2004 0:00
2820        10386  5417.57    3/1/2005 0:00

[918 rows x 3 columns]

In [16]:
df.groupby('STATUS').size()

STATUS
Cancelled       60
Disputed        14
In Process      41
On Hold         44
Resolved        47
Shipped       2617
dtype: int64

In [17]:
df[(df['YEAR_ID']==2004) & (df['QUANTITYORDERED']>30)]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,S10_1678,Auto Canal Petit,(1) 47.55.6555,"25, rue Lauriston",Paris,75016,France,Perrier,Dominique,Medium
10,10223,37,100.00,1,3965.66,2/20/2004 0:00,Shipped,1,2,2004,...,S10_1678,"Australian Collectors, Co.",03 9520 4555,636 St Kilda Road,Melbourne,3004,Australia,Ferguson,Peter,Medium
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,S10_1678,Gift Depot Inc.,2035552570,25593 South Bay Ln.,Bridgewater,97562,USA,King,Julie,Medium
14,10275,45,92.83,1,4177.35,7/23/2004 0:00,Shipped,3,7,2004,...,S10_1678,La Rochelle Gifts,40.67.8555,"67, rue des Cinquante Otages",Nantes,44000,France,Labrune,Janine,Medium
15,10285,36,100.00,6,4099.68,8/27/2004 0:00,Shipped,3,8,2004,...,S10_1678,Marta's Replicas Co.,6175558555,39323 Spinnaker Dr.,Cambridge,51247,USA,Hernandez,Marta,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2813,10293,32,60.06,1,1921.92,9/9/2004 0:00,Shipped,3,9,2004,...,S72_3212,Amica Models & Co.,011-4988555,Via Monte Bianco 34,Torino,10100,Italy,Accorti,Paolo,Small
2814,10306,35,59.51,6,2082.85,10/14/2004 0:00,Shipped,4,10,2004,...,S72_3212,"AV Stores, Co.",(171) 555-1555,Fauntleroy Circus,Manchester,EC2 5NT,UK,Ashworth,Victoria,Small
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,S72_3212,La Rochelle Gifts,40.67.8555,"67, rue des Cinquante Otages",Nantes,44000,France,Labrune,Janine,Small
2816,10327,37,86.74,4,3209.38,11/10/2004 0:00,Resolved,4,11,2004,...,S72_3212,Danish Wholesale Imports,31 12 3555,Vinb'ltet 34,Kobenhavn,1734,Denmark,Petersen,Jytte,Medium
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,S72_3212,Classic Legends Inc.,2125558493,5905 Pompton St.,NYC,10022,USA,Hernandez,Maria,Medium

In [18]:
# i want to filter the whose year  that perticular year and status id shipped and another one status is cancled i need only the mentioned columns
df[(df['YEAR_ID']==2005) & (df['STATUS']=='Shipped')][['CUSTOMERNAME','COUNTRY','ORDERNUMBER']]

                    CUSTOMERNAME  COUNTRY  ORDERNUMBER
22             La Rochelle Gifts   France        10375
23              FunGiftIdeas.com      USA        10388
24         UK Collectables, Ltd.       UK        10403
49    Collectables For Less Inc.      USA        10369
50      Corporate Gift Ideas Co.      USA        10381
...                          ...      ...          ...
2792     Oulu Toy Supplies, Inc.  Finland        10373
2794          Reims Collectables   France        10398
2795   The Sharp Gifts Warehouse      USA        10400
2819     Oulu Toy Supplies, Inc.  Finland        10373
2821                Alpha Cognac   France        10397

[354 rows x 3 columns]

In [19]:
df.groupby(['YEAR_ID','PRODUCTLINE'])['SALES'].sum()

YEAR_ID  PRODUCTLINE
2003     Classic Cars        1484785.29
         Motorcycles          370895.58
         Planes               272257.60
         Ships                244821.09
         Trains                72802.29
         Trucks and Buses     420429.93
         Vintage Cars         650987.76
2004     Classic Cars        1762257.09
         Motorcycles          560545.23
         Planes               502671.80
         Ships                341437.97
         Trains               116523.85
         Trucks and Buses     529302.89
         Vintage Cars         911423.77
2005     Classic Cars         672573.28
         Motorcycles          234947.53
         Planes               200074.17
         Ships                128178.07
         Trains                36917.33
         Trucks and Buses     178057.02
         Vintage Cars         340739.31
Name: SALES, dtype: float64

In [20]:
df.groupby('PRODUCTLINE')['PRICEEACH'].mean()

PRODUCTLINE
Classic Cars        87.335781
Motorcycles         82.997553
Planes              81.740915
Ships               83.855470
Trains              75.654675
Trucks and Buses    87.527940
Vintage Cars        78.148204
Name: PRICEEACH, dtype: float64

In [21]:
df[(df['YEAR_ID']==2003)].groupby('MONTH_ID')['SALES'].sum().idxmax()

np.int64(11)

In [22]:
df.sort_values(by='ORDERDATE').head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
475,10102,39,100.00,2,4808.31,1/10/2003 0:00,Shipped,1,1,2003,...,S18_1342,Vitachrome Inc.,2125551500,2678 Kingston Rd.,NYC,10022,USA,Frick,Michael,Medium
501,10102,41,50.14,1,2055.74,1/10/2003 0:00,Shipped,1,1,2003,...,S18_1367,Vitachrome Inc.,2125551500,2678 Kingston Rd.,NYC,10022,USA,Frick,Michael,Small
877,10366,49,100.00,2,6144.60,1/10/2005 0:00,Shipped,1,1,2005,...,S18_2870,Royale Belge,(071) 23 67 2555,"Boulevard Tirou, 255",Charleroi,B-6000,Belgium,Cartrain,Pascale,Medium
648,10366,34,100.00,3,4207.84,1/10/2005 0:00,Shipped,1,1,2005,...,S18_1984,Royale Belge,(071) 23 67 2555,"Boulevard Tirou, 255",Charleroi,B-6000,Belgium,Cartrain,Pascale,Medium
1056,10366,34,100.00,1,6275.72,1/10/2005 0:00,Shipped,1,1,2005,...,S18_3232,Royale Belge,(071) 23 67 2555,"Boulevard Tirou, 255",Charleroi,B-6000,Belgium,Cartrain,Pascale,Medium

In [23]:
df.groupby(['ORDERNUMBER','PRODUCTLINE'])['SALES'].sum().sort_values(ascending=False).head(3).reset_index()

   ORDERNUMBER   PRODUCTLINE     SALES
0        10287  Classic Cars  67281.01
1        10212  Classic Cars  65165.17
2        10310  Classic Cars  64573.72

In [24]:
df['TOTAL_PRICE']=df['PRICEEACH']*df['QUANTITYORDERED']
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,TOTAL_PRICE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small,2871.00
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small,2765.90
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium,3884.34
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium,3746.70
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium,4900.00

In [25]:
df['ORDERDATE'].str.split('/',n=1,expand=True)[0]

0        2
1        5
2        7
3        8
4       10
        ..
2818    12
2819     1
2820     3
2821     3
2822     5
Name: 0, Length: 2823, dtype: object

In [26]:
df['ORDERDATE']=pd.to_datetime(df['ORDERDATE'])
df['MONTH']=df['ORDERDATE'].dt.strftime('%b')
df.head()

#%b -->short month
#%a --> short day
#%B---> full month name
#%A---> for full day name
#%Y-->year (2024)
#%y--> year(24)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,TOTAL_PRICE,MONTH
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small,2871.00,Feb
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small,2765.90,May
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium,3884.34,Jul
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium,3746.70,Aug
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium,4900.00,Oct

In [27]:
# like same thing i want to extract the day fro that odertime
df['DAY']=df['ORDERDATE'].dt.strftime('%a')
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,TOTAL_PRICE,MONTH,DAY
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small,2871.00,Feb,Mon
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small,2765.90,May,Wed
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium,3884.34,Jul,Tue
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium,3746.70,Aug,Mon
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium,4900.00,Oct,Fri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,2004-12-02,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small,2000.00,Dec,Thu
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium,2900.00,Jan,Mon
2820,10386,43,100.00,4,5417.57,2005-03-01,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium,4300.00,Mar,Tue
2821,10397,34,62.24,1,2116.16,2005-03-28,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small,2116.16,Mar,Mon
2822,10414,47,65.52,9,3079.44,2005-05-06,On Hold,2,5,2005,...,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium,3079.44,May,Fri

In [28]:
df['PRODUCTLINE'].replace('Classic Cars','Vintage Cars').value_counts()

PRODUCTLINE
Vintage Cars        1574
Motorcycles          331
Planes               306
Trucks and Buses     301
Ships                234
Trains                77
Name: count, dtype: int64

In [36]:
df.groupby('YEAR_ID')['SALES'].sum().reset_index()

   YEAR_ID       SALES
0     2003  3516979.54
1     2004  4724162.60
2     2005  1791486.71

In [30]:
df.groupby(['PRODUCTLINE','QTR_ID'])['SALES'].sum().reset_index()

         PRODUCTLINE  QTR_ID       SALES
0       Classic Cars       1   880278.90
1       Classic Cars       2   766618.73
2       Classic Cars       3   745268.46
3       Classic Cars       4  1527449.57
4        Motorcycles       1   264385.54
5        Motorcycles       2   277822.27
6        Motorcycles       3   213194.70
7        Motorcycles       4   410985.83
8             Planes       1   234356.51
9             Planes       2   247054.75
10            Planes       3   143052.95
11            Planes       4   350539.36
12             Ships       1   203877.30
13             Ships       2   143114.28
14             Ships       3   120498.22
15             Ships       4   246947.33
16            Trains       1    58115.80
17            Trains       2    35284.87
18            Trains       3    39450.16
19            Trains       4    93392.64
20  Trucks and Buses       1   208619.04
21  Trucks and Buses       2   240838.42
22  Trucks and Buses       3   199511.01
23  Trucks and Buses       4   478821.37
24      Vintage Cars       1   501184.64
25      Vintage Cars       2   337386.98
26      Vintage Cars       3   297935.31
27      Vintage Cars       4   766643.91

In [35]:
df.groupby('PRODUCTLINE')['MSRP'].mean().reset_index()

        PRODUCTLINE        MSRP
0      Classic Cars  119.885212
1       Motorcycles   97.069486
2            Planes   88.767974
3             Ships   86.128205
4            Trains   72.987013
5  Trucks and Buses  102.465116
6      Vintage Cars   86.461285

In [37]:
df.groupby('PRODUCTLINE')['QUANTITYORDERED'].sum().reset_index()

        PRODUCTLINE  QUANTITYORDERED
0      Classic Cars            33992
1       Motorcycles            11663
2            Planes            10727
3             Ships             8127
4            Trains             2712
5  Trucks and Buses            10777
6      Vintage Cars            21069

In [33]:
df[df['YEAR_ID']==2003].groupby('QTR_ID')['QUANTITYORDERED'].size()

QTR_ID
1    130
2    162
3    184
4    524
Name: QUANTITYORDERED, dtype: int64

In [34]:
df[df['YEAR_ID']==2005].groupby('ORDERNUMBER')['SALES'].sum().sort_values(ascending=False).head(1).reset_index()

   ORDERNUMBER     SALES
0        10390  61133.28